#!/usr/bin/env python3
"""
apply_patch.py -- applies the phone-independent ramp patch to your own,
locally-obtained Carta 2 (Quantum) firmware dump.

This script does NOT contain, download, or embed any Focus V firmware. You
supply your own firmware file (the full file as downloaded from Focus V's own
update infrastructure, header included -- see docs/ble-protocol.md and
docs/firmware-architecture.md in this repo for where that comes from). The
script only contains our own compiled code (ramp_firmware_v1.bin, built from
ramp_tick.c/ramp_save.c/ramp_display.c in this same directory) and a handful
of small "patch bytes" -- replacement machine-code instructions, the same
size as what they replace, at specific addresses. This is the same model as
an IPS/BPS ROM-hacking patch: distributing *only* the diff, never the base
copyrighted file. See ../LEGAL.md.

Usage:
    python3 apply_patch.py --input your-firmware.bin --output patched.bin

The output is a complete, OTA-flashable image (header + body + a freshly
computed Telink CRC32 trailer) -- push it with tools/ota-flash.html, or keep
your original file to push back at any time for a full, clean revert. This
has NOT been tested on real hardware yet; see the main README's status note
before flashing a device you depend on.
"""

import argparse
import hashlib
import struct
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

# Confirmed Carta 2 "PROD-111224" build fingerprint -- first 12 hex chars of
# the SHA-1 of the complete file exactly as downloaded (header included), see
# docs/firmware-architecture.md. This is a sanity check, not a hard
# requirement: a different build will very likely have these exact call
# sites at different addresses, so proceeding anyway is very likely to
# corrupt the image rather than patch it cleanly.
EXPECTED_SHA1_PREFIX = "a6b741dc0508"
EXPECTED_BODY_LEN = 143564  # bytes, header excluded

HEADER_LEN = 40
KNLT_OFFSET = 8
LENGTH_FIELD_OFFSET = 24

# Flash sector this patch's own code lives in (confirmed free space ahead of
# the OTA staging area -- see firmware-architecture.md). The image is grown
# to cover this whole sector plus the waypoint-storage sector right after it.
CODE_INJECT_ADDR = 0x30000
IMAGE_END_ADDR = 0x32000

CODE_BLOB_PATH = SCRIPT_DIR / "ramp_firmware_v1.bin"

# Each entry: (patch address, expected original bytes, replacement bytes).
# The expected-original check is what keeps this script from silently
# corrupting a firmware build these addresses weren't confirmed against --
# if your file doesn't match, the script stops instead of guessing.
#
# All seven are same-length call-site swaps -- a single `tjl <addr>`
# instruction replaced with another `tjl <addr>` of identical length (4
# bytes each). Nothing is inserted or removed, so every other byte in the
# image is untouched. See ramp_tick.c/ramp_save.c/ramp_display.c for what
# each replacement actually does.
#
# Every address below was independently re-confirmed directly against the
# real PROD-111224 binary -- not carried over from an earlier build. Two of
# them (the PID-tick call site and the marker-dispatch call site) required
# real additional work to get right: an earlier draft of this patch had both
# at stale addresses inherited from a different, older firmware build. The
# PID-tick call site (0x6e2e) was ultimately confirmed by an exhaustive scan
# -- checking every possible 4-byte-aligned position in the entire
# 143,564-byte firmware for a `tjl 0xaf2c` encoding, generated by the real
# assembler, not guessed -- which found exactly one match in the whole file.
# The marker-dispatch site turned out to need a different approach entirely:
# the real BLE marker-check code only reaches any given marker's handler
# (0xA5/0xAF/0x66) through a fixed compare chain that the five new
# ramp-waypoint markers (0xB1-0xB5) never match, so this patch intercepts
# the marker *load*, before that chain runs, not any single leaf of it --
# see ramp_save.c and marker_entry.s (renamed from the single-leaf version
# this folder shipped with a different, stale address, before this
# correction) for the full reasoning.
#
# Two more sites (0xfa3c, 0xfa58) were added in a later revision after an
# audit of this already-shipped patch found FUN_0000dcac and FUN_0000e300 --
# two more elements FUN_0000fa1c draws every tick -- were never suppressed
# by the original 5-patch version, despite drawing inside the graph's own
# screen area. See ramp_display.c's header for the full story. Adding them
# shifted every address inside the injected code blob (new functions moved
# everything after them), so all five of the *original* replacement values
# below changed too, even though their patch addresses and original/expected
# bytes didn't -- every one of the 7 replacement values here was regenerated
# fresh from the real assembler against the rebuilt blob, not hand-adjusted.
PATCHES = [
    # PID-tick call site -> ramp_trampoline, which runs the original
    # per-tick PID/session orchestrator (FUN_0000af2c) unmodified, then the
    # ramp sequencer.
    (0x6e2e, bytes.fromhex("04907d98"), bytes.fromhex("2990e798")),
    # Marker-byte load, just before the stock A5/AF/66 compare chain inside
    # the 0xCC handler's marker dispatch -> ramp_marker_entry, which
    # replicates that same load (so the untouched chain right after this
    # call site keeps working exactly as before for every marker value this
    # patch doesn't care about), and in between, calls ramp_marker_dispatch
    # to handle the five new waypoint-save markers.
    (0x11d96, bytes.fromhex("28a3eb1c"), bytes.fromhex("1e90bf9c")),
    # Live-heating-screen temp display -> ramp_temp_display (graph when a
    # ramp is active, original dial otherwise).
    (0xfa38, bytes.fromhex("fd97c29c"), bytes.fromhex("2090629c")),
    # Secondary temp+gauge display -> ramp_secondary_or_skip (suppressed
    # during a ramp -- this is one of the two gap sites, see above; left
    # unpatched it draws its own digits over the graph's right-hand side).
    (0xfa3c, bytes.fromhex("fe973699"), bytes.fromhex("20903a9e")),
    # Session countdown timer -> ramp_countdown_or_skip (suppressed during a
    # ramp -- it doesn't apply once a ramp has its own per-stage timing).
    (0xfa50, bytes.fromhex("fd97fa9a"), bytes.fromhex("20903c9e")),
    # Active-preset badge -> ramp_badge_or_skip (suppressed during a ramp,
    # freeing that screen space for the stage-digit indicator instead).
    (0xfa54, bytes.fromhex("fe97ea9c"), bytes.fromhex("2090469e")),
    # Lower-row status icon -> ramp_status_icon_or_skip (suppressed during a
    # ramp -- the other gap site; left unpatched it redraws an icon in the
    # same row the countdown/badge above are already suppressed in).
    (0xfa58, bytes.fromhex("fe97529c"), bytes.fromhex("2090509e")),
]


def telink_crc32(data: bytes) -> int:
    """Reflected CRC32, poly 0xEDB88320, init 0xFFFFFFFF, NO final XOR --
    confirmed against both official Focus V images' own trailers (see
    firmware-architecture.md). This is *not* the same as zlib.crc32()."""
    crc = 0xFFFFFFFF
    for byte in data:
        crc ^= byte
        for _ in range(8):
            crc = (crc >> 1) ^ 0xEDB88320 if crc & 1 else crc >> 1
    return crc & 0xFFFFFFFF


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input", required=True, type=Path, help="your own stock firmware file (header included)")
    parser.add_argument("--output", required=True, type=Path, help="where to write the patched, OTA-ready image")
    parser.add_argument(
        "--force",
        action="store_true",
        help="apply the patch even if the input doesn't match the confirmed build fingerprint",
    )
    args = parser.parse_args()

    raw = args.input.read_bytes()
    if len(raw) < HEADER_LEN + 4:
        print("error: that file is too small to be a real firmware image", file=sys.stderr)
        return 1

    magic = raw[KNLT_OFFSET : KNLT_OFFSET + 4]
    if magic != b"KNLT":
        print(f'error: no "KNLT" header at byte 8 (found {magic!r}) -- is this the right file?', file=sys.stderr)
        return 1

    header = bytearray(raw[:HEADER_LEN])
    # Everything after the header, exactly as downloaded -- including Focus V's
    # own trailer, if this build has one. It doesn't need to be identified or
    # stripped: every patch site sits well before the injected-code sector at
    # 0x30000, so whatever's in the original file's last few bytes just ends up
    # harmlessly inside the 0xFF-padded gap before that sector in the output,
    # and a fresh trailer covering the *whole* new image is computed below
    # regardless of whether one was present going in.
    body = bytearray(raw[HEADER_LEN:])

    fingerprint = hashlib.sha1(bytes(raw)).hexdigest()[:12]
    if fingerprint != EXPECTED_SHA1_PREFIX or len(body) != EXPECTED_BODY_LEN:
        print(
            "warning: this doesn't match the exact build these patch addresses were confirmed\n"
            f"against (PROD-111224, fingerprint {EXPECTED_SHA1_PREFIX}, {EXPECTED_BODY_LEN} bytes).\n"
            f"got fingerprint {fingerprint}, {len(body)} bytes. a different build likely has these\n"
            "call sites at different addresses -- applying this patch anyway will probably corrupt\n"
            "the image rather than patch it cleanly.",
            file=sys.stderr,
        )
        if not args.force:
            print("refusing to continue without --force.", file=sys.stderr)
            return 1
        print("--force given, continuing anyway.", file=sys.stderr)

    for addr, expected, replacement in PATCHES:
        n = len(expected)
        actual = bytes(body[addr : addr + n])
        if actual != expected:
            print(
                f"error: byte mismatch at {addr:#x} -- expected {expected.hex()}, found {actual.hex()}.\n"
                "this firmware doesn't match what this patch was built for; refusing to touch it.",
                file=sys.stderr,
            )
            return 1

    for addr, _expected, replacement in PATCHES:
        body[addr : addr + len(replacement)] = replacement

    if len(body) < IMAGE_END_ADDR:
        body.extend(b"\xff" * (IMAGE_END_ADDR - len(body)))

    code_blob = CODE_BLOB_PATH.read_bytes()
    if CODE_INJECT_ADDR + len(code_blob) > IMAGE_END_ADDR:
        print("error: injected code blob no longer fits its reserved sector", file=sys.stderr)
        return 1
    body[CODE_INJECT_ADDR : CODE_INJECT_ADDR + len(code_blob)] = code_blob

    total_len = HEADER_LEN + len(body) + 4
    struct.pack_into("<I", header, LENGTH_FIELD_OFFSET, total_len)

    payload = bytes(header) + bytes(body)
    trailer = struct.pack("<I", telink_crc32(payload))
    final_image = payload + trailer

    args.output.write_bytes(final_image)
    print(f"wrote {args.output} ({len(final_image)} bytes)")
    print("keep your original input file -- push it back with tools/ota-flash.html any time to revert.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
