#!/usr/bin/env python3
"""
make_logo.py -- turns the Terpline logo into carta2/logo_strip.h: the small
multi-colour strip (flame mark + "Terpline" wordmark) drawn under the Carta 2
ramp chart.

The firmware can only draw solid rectangles and one-colour bitmaps, so the
strip is stored as horizontal runs -- (x, length, row, colour) -- each drawn
with one fill_rect, in a palette of a few flat brand colours.

Usage:
    python3 tools/make_logo.py --logo "path/to/logo 192.png" [--preview strip.png]
"""
import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent

STRIP_W, STRIP_H = 240, 23          # drawn at x 0-239, y 202-224 on the device
STRIP_Y = 202
MARK_H = 23                         # flame mark height, px
WORD_PX = 21                        # wordmark font size, px

# flat brand colours sampled from the logo's flame: cyan -> green -> yellow -> orange
PALETTE = [(0, 190, 210), (40, 200, 70), (240, 220, 20), (255, 135, 0)]

FONTS = ["C:/Windows/Fonts/segoeuib.ttf", "C:/Windows/Fonts/arialbd.ttf",
         "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"]


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def nearest(rgb):
    return min(range(len(PALETTE)), key=lambda i: sum((a - b) ** 2 for a, b in zip(rgb, PALETTE[i])))


def flame_mark(logo_path):
    """The flame + leaf, cropped from inside the badge ring, as palette indices."""
    im = Image.open(logo_path).convert("RGBA")
    w, h = im.size
    box = (int(w * 0.31), int(h * 0.10), int(w * 0.705), int(h * 0.585))
    crop = im.crop(box)
    cw, ch = crop.size
    out_w = max(1, round(cw * MARK_H / ch))
    small = crop.resize((out_w, MARK_H), Image.LANCZOS)
    px = {}
    for y in range(MARK_H):
        for x in range(out_w):
            r, g, b, a = small.getpixel((x, y))
            if a < 128 or max(r, g, b) < 95 or max(r, g, b) - min(r, g, b) < 55:
                continue                    # background / dark outline
            px[(x, y)] = nearest((r, g, b))
    return px, out_w


def wordmark():
    """'Terpline' in a bold sans, coloured by a left-to-right sweep through the palette."""
    font = next((ImageFont.truetype(f, WORD_PX) for f in FONTS if Path(f).exists()), None)
    if font is None:
        raise SystemExit("no bold TrueType font found -- edit FONTS")
    x0, y0, x1, y1 = font.getbbox("Terpline")
    tw, th = x1 - x0, y1 - y0
    mask = Image.new("L", (tw, th), 0)
    ImageDraw.Draw(mask).text((-x0, -y0), "Terpline", font=font, fill=255)
    px = {}
    for y in range(th):
        for x in range(tw):
            if mask.getpixel((x, y)) >= 128:
                px[(x, y)] = min(len(PALETTE) - 1, x * len(PALETTE) // tw)
    return px, tw, th


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--logo", required=True)
    ap.add_argument("--preview")
    a = ap.parse_args()

    mark, mw = flame_mark(a.logo)
    word, ww, wh = wordmark()
    gap = 6
    left = 6                         # the screen's common left edge
    pix = {}
    for (x, y), c in mark.items():
        pix[(left + x, y)] = c
    wy = (STRIP_H - wh) // 2
    for (x, y), c in word.items():
        pix[(left + mw + gap + x, wy + y)] = c

    runs = []
    for y in range(STRIP_H):
        x = 0
        while x < STRIP_W:
            c = pix.get((x, y))
            if c is None:
                x += 1
                continue
            n = 1
            while x + n < STRIP_W and pix.get((x + n, y)) == c:
                n += 1
            runs.append((x, n, y, c))
            x += n
    assert STRIP_H <= 32 and len(PALETTE) <= 8   # row and colour share one byte

    # "DABS" label for the dab counter, a hand-drawn 5 x 7 pixel font so it
    # stays crisp at this size; drawn by the firmware just left of the count
    glyphs = {
        "D": ["11110", "10001", "10001", "10001", "10001", "10001", "11110"],
        "A": ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
        "B": ["11110", "10001", "10001", "11110", "10001", "10001", "11110"],
        "S": ["01111", "10000", "10000", "01110", "00001", "00001", "11110"],
    }
    label = {}
    for k, ch in enumerate("DABS"):
        for y, row in enumerate(glyphs[ch]):
            for x, bit in enumerate(row):
                if bit == "1":
                    label[(k * 6 + x, y)] = 0
    label_w, label_h = 4 * 6 - 1, 7
    label_runs = []
    for y in range(label_h):
        x = 0
        while x < label_w:
            if (x, y) not in label:
                x += 1
                continue
            n = 1
            while (x + n, y) in label:
                n += 1
            label_runs.append((x, n, y))
            x += n

    lines = [
        "/* logo_strip.h -- generated by tools/make_logo.py from the Terpline logo; do not edit.",
        " * The flame mark + \"Terpline\" wordmark as horizontal runs, one fill_rect each:",
        " * {x, length, row << 3 | colour}. */",
        f"#define LOGO_Y      {STRIP_Y}",
        f"#define LOGO_H      {STRIP_H}",
        f"#define LOGO_RUNS   {len(runs)}",
        "static const u16 LOGO_PAL[" + str(len(PALETTE)) + "] = { " +
        ", ".join(f"0x{rgb565(*c):04X}" for c in PALETTE) + " };",
        "static const u8 LOGO_RUN[LOGO_RUNS][3] = {",
    ]
    for i in range(0, len(runs), 6):
        lines.append("    " + " ".join(f"{{{x},{n},{(y << 3) | c}}}," for x, n, y, c in runs[i:i + 6]))
    lines.append("};")
    lines += [
        f"#define LOGO_W      {left + mw + gap + ww}   /* the logo ends here; the dab count is right of it */",
        f"#define LABEL_W     {label_w}",
        f"#define LABEL_H     {label_h}",
        f"#define LABEL_RUNS  {len(label_runs)}",
        "static const u8 LABEL_RUN[LABEL_RUNS][3] = {   /* \"DABS\": {x, length, row} */",
    ]
    for i in range(0, len(label_runs), 8):
        lines.append("    " + " ".join(f"{{{x},{n},{y}}}," for x, n, y in label_runs[i:i + 8]))
    lines.append("};")
    (REPO / "carta2" / "logo_strip.h").write_text("\n".join(lines) + "\n", newline="\n")
    print(f"logo_strip.h: {len(runs)} runs, {len(runs) * 3 + len(PALETTE) * 2} bytes; mark {mw}px + wordmark {ww}x{wh}px")

    if a.preview:
        img = Image.new("RGB", (STRIP_W, STRIP_H))
        for (x, y), c in pix.items():
            img.putpixel((x, y), PALETTE[c])
        img.resize((STRIP_W * 4, STRIP_H * 4), Image.NEAREST).save(a.preview)


if __name__ == "__main__":
    main()
